
import Image from "next/image";

export const metadata = {
  title: 'Home | App',
  description: 'Generated by create next app',
}

const HomePage: React.FC = () => {
  return (
    <div className="flex-col">

      <div className="bg-customColor-100">
        <div className="flex container justify-between mx-auto p-2" >
          <p className="text-white font-bold text-sm">
            info@e-liquids.com | 0121 272 2900
          </p>
          <Image src='./trustpilot-logo.svg' alt="trustpilot" width={180} height={21} />
        </div >
      </div>

      <div className="flex justify-between container mx-auto">
        <Image src='./logo.svg' alt="trustpilot" width={170} height={36} />
      </div>

    </div>
  )
}

export default HomePage;