import { MainLayout } from '@/components/layouts';

export const metadata = {
  title: 'Home | App',
  description: 'Generated by create next app',
}

const HomePage: React.FC = () => {
  return (
    <MainLayout>
      <div>HomePage</div>
    </MainLayout>
  )
}

export default HomePage;