
export const metadata = {
  title: 'Home | App',
  description: 'Generated by create next app',
}

const HomePage: React.FC = () => {
  return (
    <div className="container mx-auto">
      <div>
        <div>HomePage</div>
      </div>
    </div>
  )
}

export default HomePage;